---
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/git"
    - message: "chore(release): ${nextRelease.version} [skip ci]"
  - "@semantic-release/github"
