---
preset: conventionalcommits
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: docs
          release: patch
  - - "@semantic-release/release-notes-generator"
    - presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: docs
            section: Documentation
          - type: chore
            hidden: true
          - type: style
            hidden: true
          - type: refactor
            hidden: true
          - type: perf
            hidden: true
          - type: test
            hidden: true
  - - "@semantic-release/changelog"
    - changelogFile: "docs/CHANGELOG.md"
  - - "@semantic-release/git"
    - assets:
        - docs/CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]"
  - - "@semantic-release/exec"
    - publishCmd: |
        echo "${nextRelease.notes}" > /tmp/release-notes.md
        goreleaser release --release-notes /tmp/release-notes.md --clean
