---
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: "docs/CHANGELOG.md"
  - - "@semantic-release/git"
    - assets:
        - docs/CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]"
  # - - "@semantic-release/exec"
  #   - publishCmd: |
  #       echo "${nextRelease.notes}" > /tmp/notes.md
  #       echo "\n\nFrom Me" >> /tmp/notes.md
  - - "@semantic-release/github"
    - releaseBodyTemplate: |
        <%= nextRelease.notes %>

        ---

        Your mum!!!
