#!/usr/bin/env bash

set -euo pipefail

WORKFLOW="release.yaml"
BRANCH="main"

gh workflow run "$WORKFLOW" -r "$BRANCH"

RUN_ID=$(
  gh run list \
    --workflow "$WORKFLOW" \
    --branch "$BRANCH" \
    --limit 1 \
    --json databaseId \
    --jq '.[0].databaseId'
)

gh run watch "$RUN_ID" && {
  echo "Fetching latest changes..."
  git fetch origin "$BRANCH"
  git fetch --tags
}

echo "✅ Repo is up to date with release commit and tags."
