---
name: release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
